### ISSUE TITLE
Flutter app does not receive the response after first time

### ISSUE THREAD

**Issue by hivesey** [jamiewest/sse_client#1]
Hi,

Thanks for your library, I have used it as below;

SseClient.connect(url).stream.listen();

What I notice is that when I post from the server, the client gets the response the first time around but the consecutive responses are lost (never received by the flutter client app).

Has anyone else noticed this? Am I missing anything?

Thanks,

**Comment by hivesey** [comment]
Works fine. I guess leak/not closed stream listener might have caused some issues

**Comment by jamiewest** [comment]
Sorry I meant to respond sooner. Glad it's working?.. This library is primarily designed to work with my SignalR client and does not strictly adhere to the SSE spec.
