### ISSUE TITLE
Documantaion?

### ISSUE THREAD

**Issue by privateGenish** [jamiewest/sse_client#2]
This package is quite important!
SSE is something flutter is yet to provide default support..
could you please atleast explain how to use the package proparly?

**Comment by jamiewest** [comment]
Thank you for interest in this library. This code was designed to be consumed by my [signalr_core](https://pub.dev/packages/signalr_core) package which is also compatible on the web. As such it was not intended to be a fully featured implementation. I would recommend you look at [sse](https://github.com/dart-lang/sse)
